import {createGame,step,startWave,chooseUpgrade,ability,UPGRADES} from './engine.mjs';
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d');
const names={damage:['增幅透鏡','雷射傷害 ×1.24，可累加','✧'],rate:['急速電容','射擊速度 ×1.20，所有砲台適用','ϟ'],chain:['電弧連鎖','以 60% 傷害連鎖一個額外目標','⌁'],pierce:['穿甲光束','以 70% 傷害穿透一個額外目標','↟'],frost:['低溫核心','凍緩敵人，爭取更多射擊時間','❄'],turret:['僚機砲台','增設火力支援，擴大攻擊覆蓋','⫷'],repair:['緊急維修','艦體 +40、最大艦體 +12、護盾補滿','✚'],shield:['護盾矩陣','護盾容量 +25，提高自動回復','⬡'],reactor:['高效反應爐','能量回復 +30%，能量容量 +15','⊙'],critical:['精密校準','暴擊機率 +15%，暴擊造成雙倍傷害','⌖']};
let g=createGame(7307),paused=false,screen='title',aim={firing:true},last=0,acc=0,clock=0,seenKills=new Set(),particles=[],best=0,muted=true,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,audio;
try{best=+localStorage.getItem('auroraBest')||0;muted=localStorage.getItem('auroraSound')!=='on';reduced=localStorage.getItem('auroraReduced')==='true'||reduced}catch{}
$('best').textContent=String(best).padStart(6,'0');
const panel=(content)=>{$('overlay').innerHTML=`<div class="panel">${content}</div>`};
const button=(id,text,cls='primary')=>`<button id="${id}" class="${cls}">${text}</button>`;
function bind(id,fn){const e=$(id);if(e)e.onclick=fn}
function sound(freq=400,duration=.06,volume=.018){if(muted)return;try{audio??=new AudioContext();audio.resume();const o=audio.createOscillator(),a=audio.createGain();o.type='sine';o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.55,audio.currentTime+duration);a.gain.setValueAtTime(volume,audio.currentTime);a.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(a).connect(audio.destination);o.start();o.stop(audio.currentTime+duration)}catch{}}
function title(){screen='title';panel(`<div class="sigil">✳</div><div class="eyebrow">ORBITAL DEFENSE / CAMPAIGN 07</div><h2>極光軌道</h2><p>守住最後的星港。<br>以雷射、改裝與戰術，抵禦 12 波來襲。</p>${button('launch','啟動防線 →')}${button('instructions','首次出擊？查看操作','secondary')}<p class="fine">原創單人遊戲 · 不需下載 · 約 3–5 分鐘</p>`);bind('launch',newRun);bind('instructions',()=>openInfo('help'))}
function newRun(){g=createGame(7307);startWave(g);paused=false;screen='running';particles=[];seenKills.clear();aim={firing:true};$('overlay').innerHTML='';$('pause').textContent='Ⅱ';announce(`WAVE 01 / 防線啟動`);sound(600,.2);sync()}
let announceUntil=0;
function announce(text){$('announcement').textContent=text;$('announcement').classList.add('show');announceUntil=clock+2.5}
function showUpgrade(){screen='upgrade';const choices=g.choices||[];panel(`<div class="eyebrow">SECTOR ${String(g.wave).padStart(2,'0')} SECURED</div><h2>改裝時間</h2><p>每波只能選擇一項。<br>讓模組協同，建立你的戰術。</p>${choices.map((id,i)=>{const n=names[id]||[id,'強化防線','✧'];return `<button class="upgrade" data-choice="${id}"><em>${n[2]}</em><span><strong>${n[0]}</strong><small>${n[1]}</small></span><b>${i+1}</b></button>`}).join('')}<p class="fine">點選即進入下一波 · 鍵盤 1 / 2 / 3</p>`);document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>pick(b.dataset.choice))}
function pick(id){if(g.state!=='upgrade'||!g.choices.includes(id))return;chooseUpgrade(g,id);screen='running';$('overlay').innerHTML='';announce(`WAVE ${String(g.wave).padStart(2,'0')} / ${g.wave%4===0?'巨大訊號接近':'敵群接近'}`);sound(720,.13);sync()}
function end(){screen=g.state;best=Math.max(best,Math.floor(g.score));try{localStorage.setItem('auroraBest',best)}catch{}$('best').textContent=String(best).padStart(6,'0');const win=g.state==='victory';panel(`<div class="sigil">${win?'✦':'◇'}</div><div class="eyebrow">${win?'MISSION COMPLETE':'SIGNAL LOST'}</div><h2>${win?'黎明，仍在。':'防線失守'}</h2><p>${win?'十二波敵軍已全數擊退。<br>星港的燈，再次為你亮起。':'星港記住了你的抵抗。<br>試試連鎖與穿透，並保留能量應對危機。'}</p><div class="result-stat"><span>總得分<strong>${Math.floor(g.score)}</strong></span><span>抵達波次<strong>${g.wave} / 12</strong></span></div>${button('retry',win?'再次出擊 →':'重新建立防線 →')}${button('return','返回主畫面','secondary')}`);bind('retry',newRun);bind('return',()=>{g=createGame(7307);paused=false;title();sync()});sound(win?880:130,.5)}
function pauseGame(){if(g.state!=='running')return;if(paused){closeInfo();return}paused=true;screen='pause';$('pause').textContent='▶';panel(`<div class="eyebrow">SYSTEMS ON HOLD</div><h2>戰場已暫停</h2><p>稍作喘息。所有敵軍與射擊均已停止。</p>${button('resume','繼續防守 →')}${button('restartAsk','重新開始','secondary')}`);bind('resume',closeInfo);bind('restartAsk',()=>{panel(`<h2>重新出擊？</h2><p>本次戰役進度將會重置。</p>${button('restartYes','確認重新開始')}${button('restartNo','繼續目前戰役','secondary')}`);bind('restartYes',newRun);bind('restartNo',closeInfo)})}
function closeInfo(){paused=false;$('pause').textContent='Ⅱ';if(g.state==='title'){title();return}screen=g.state;if(g.state==='running')$('overlay').innerHTML='';else if(g.state==='upgrade')showUpgrade();else end()}
function openInfo(which){paused=true;screen=which;$('pause').textContent='▶';if(which==='help'){panel(`<div class="eyebrow">PILOT BRIEFING</div><h2>操作指南</h2><p>砲台會自動索敵。按住戰場並拖曳，讓雷射集中攻擊游標附近的敵人；放開恢復自動瞄準。<br><br>◎ 電磁脈衝：35 能量，傷害敵群；冷卻 12 秒。<br>ϟ 雷射超載：50 能量，強化火力 6 秒；冷卻 16 秒。<br>空白鍵使用脈衝，E 使用超載，P / Esc 暫停。<br><br>青色斥候、重裝甲艦、分裂機群各有威脅。每 4 波會出現頭目。每波結束選一項改裝；保護艦體，擊退第 12 波即可獲勝。<br><br>護盾可承受傷害。艦體歸零即失敗。拖曳時有集中火力加成；別忘了把能量用在最危險的時刻。</p>${button('closeInfo','了解，返回 →')}`)}else{panel(`<div class="eyebrow">PREFERENCES</div><h2>系統設定</h2><label class="setting">音效<input id="soundToggle" type="checkbox" ${muted?'':'checked'}></label><label class="setting">減少動態效果<input id="motionToggle" type="checkbox" ${reduced?'checked':''}></label><p class="fine">設定會儲存於這台裝置。<br>減少動態會移除粒子與裝飾動畫。</p>${button('closeInfo','返回 →')}`);$('soundToggle').onchange=e=>{muted=!e.target.checked;try{localStorage.setItem('auroraSound',muted?'off':'on')}catch{}sound(650,.1)};$('motionToggle').onchange=e=>{reduced=e.target.checked;try{localStorage.setItem('auroraReduced',reduced)}catch{}}}bind('closeInfo',closeInfo)}
function cast(kind){if(paused||g.state!=='running')return;const ok=ability(g,kind);if(ok){sound(kind==='pulse'?160:550,.3);announce(kind==='pulse'?'PULSE / 電磁脈衝':'OVERDRIVE / 雷射超載');sync()}}
$('pause').onclick=pauseGame;$('pulse').onclick=()=>cast('pulse');$('overdrive').onclick=()=>cast('overdrive');$('help').onclick=()=>openInfo('help');$('settings').onclick=()=>openInfo('settings');
function point(e){const r=canvas.getBoundingClientRect();aim.aimX=(e.clientX-r.left)*480/r.width;aim.aimY=(e.clientY-r.top)*700/r.height}
canvas.onpointerdown=e=>{if(g.state!=='running'||paused)return;canvas.setPointerCapture(e.pointerId);point(e);canvas.focus()};canvas.onpointermove=e=>{if(canvas.hasPointerCapture(e.pointerId))point(e)};function release(){delete aim.aimX;delete aim.aimY}canvas.onpointerup=release;canvas.onpointercancel=release;canvas.onlostpointercapture=release;
window.addEventListener('keydown',e=>{if(e.target instanceof HTMLInputElement)return;const k=e.key.toLowerCase();if(k===' '){e.preventDefault();if(!e.repeat)cast('pulse')}else if(k==='e'&&!e.repeat)cast('overdrive');else if((k==='p'||k==='escape')&&!e.repeat){if(screen==='help'||screen==='settings')closeInfo();else pauseGame()}else if(['1','2','3'].includes(k)&&g.state==='upgrade'&&!paused)pick(g.choices[+k-1]);});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&g.state==='running'&&!paused)pauseGame();last=0;acc=0});window.addEventListener('blur',release);
function sync(){const hp=g.hp??100,shield=g.shield??40,energy=g.energy??100;$('wave').innerHTML=`${String(g.wave).padStart(2,'0')}<span> / 12</span>`;$('score').textContent=String(Math.floor(g.score||0)).padStart(6,'0');for(const [id,value,max]of[['hp',hp,g.maxHp||100],['shield',shield,g.maxShield||40],['energy',energy,g.maxEnergy||100]]){$(`${id}Text`).textContent=Math.ceil(value);$(`${id}Bar`).style.width=`${Math.max(0,Math.min(100,value/max*100))}%`}$('pulse').disabled=g.state!=='running'||paused||energy<35||g.pulseCooldown>0;$('overdrive').disabled=g.state!=='running'||paused||energy<50||(g.overdrive||0)>0||g.overdriveCooldown>0;$('pulse').querySelector('small').textContent=g.pulseCooldown>0?`冷卻 ${Math.ceil(g.pulseCooldown)} 秒`:'35 能量 · 空白鍵';$('overdrive').querySelector('small').textContent=g.overdrive>0?`超載中 ${Math.ceil(g.overdrive)} 秒`:g.overdriveCooldown>0?`冷卻 ${Math.ceil(g.overdriveCooldown)} 秒`:'50 能量 · E';$('mode').textContent=aim.aimX!=null?'FOCUS-LOCK ◉':'AUTO-LOCK ●';$('sector').textContent=g.wave<=4?'外環 / APPROACH':g.wave<=8?'內環 / BREACH':'核心 / LAST LIGHT';$('status').textContent=paused?'系統暫停':g.state==='running'?`${g.wave%4===0?'頭目訊號 · ':''}敵軍 ${g.enemies?.length||0} · 拖曳集中火力`:g.state==='upgrade'?'選擇改裝，繼續前進':g.state==='victory'?'星港安全 · 任務完成':g.state==='defeat'?'防線失守':'系統待命';const upgrades=g.upgrades||g.mods||{};$('modules').innerHTML='<li>標準雷射陣列 <b>MK. I</b></li>'+Object.entries(upgrades).filter(([id,n])=>n>0&&names[id]).map(([id,n])=>`<li>${names[id][0]} <b>× ${n}</b></li>`).join('')}
const stars=Array.from({length:80},(_,i)=>({x:(i*137.508)%480,y:(i*79.711)%700,r:i%5===0?1.3:.65}));
function line(x1,y1,x2,y2,color,width=1){ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke()}
function draw(){ctx.clearRect(0,0,480,700);const bg=ctx.createRadialGradient(240,250,0,240,300,540);bg.addColorStop(0,'#152232');bg.addColorStop(.55,'#0a1320');bg.addColorStop(1,'#060c15');ctx.fillStyle=bg;ctx.fillRect(0,0,480,700);for(const s of stars){ctx.fillStyle=`rgba(165,201,218,${.15+(s.r/4)})`;ctx.beginPath();ctx.arc(s.x,(s.y+(reduced?0:clock*2))%700,s.r,0,Math.PI*2);ctx.fill()}
ctx.save();ctx.translate(240,-140);for(let i=0;i<9;i++){ctx.beginPath();ctx.arc(0,0,200+i*58+(reduced?0:Math.sin(clock*.25)*5),0,Math.PI);ctx.strokeStyle=`rgba(238,133,174,${.11+i*.009})`;ctx.lineWidth=i%3===0?1.6:.8;ctx.stroke()}ctx.restore();for(let x=0;x<=480;x+=48)line(x,580,x,700,'#24434c20');for(let y=590;y<700;y+=24)line(0,y,480,y,'#24434c30');
ctx.fillStyle='#102634';ctx.beginPath();ctx.moveTo(0,676);ctx.lineTo(60,645);ctx.lineTo(140,663);ctx.lineTo(195,631);ctx.lineTo(285,631);ctx.lineTo(340,663);ctx.lineTo(420,645);ctx.lineTo(480,676);ctx.lineTo(480,700);ctx.lineTo(0,700);ctx.fill();line(0,676,60,645,'#486064');line(60,645,140,663,'#486064');line(140,663,195,631,'#486064');line(195,631,285,631,'#8ea99a');line(285,631,340,663,'#486064');line(340,663,420,645,'#486064');line(420,645,480,676,'#486064');
if((g.shield||0)>0){ctx.beginPath();ctx.ellipse(240,680,282,82,0,Math.PI,2*Math.PI);ctx.strokeStyle=`rgba(103,218,230,${.15+.2*(g.shield/(g.maxShield||40))})`;ctx.lineWidth=2;ctx.stroke()}
const turrets=g.turrets?.length?g.turrets:[{x:110,y:642},{x:240,y:631},{x:370,y:642}];for(const t of turrets){ctx.save();ctx.translate(t.x,t.y);ctx.fillStyle='#162c38';ctx.strokeStyle='#5b7782';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(-18,15);ctx.lineTo(-14,-7);ctx.lineTo(0,-16);ctx.lineTo(14,-7);ctx.lineTo(18,15);ctx.closePath();ctx.fill();ctx.stroke();ctx.rotate((t.angle??-Math.PI/2)+Math.PI/2);ctx.fillStyle='#6f9090';ctx.fillRect(-5,-31,10,27);ctx.fillStyle='#d5f9ac';ctx.fillRect(-2,-35,4,15);ctx.restore()}
for(const e of g.enemies||[]){ctx.save();ctx.translate(e.x,e.y);const r=e.radius||e.r||12,type=e.type;const color=type==='boss'?'#f494ba':type==='armor'?'#e9b279':type==='splitter'?'#bf9fee':'#8fcbd1';ctx.strokeStyle=color;ctx.fillStyle=type==='boss'?'#431f3e':'#19303c';ctx.lineWidth=1.6;ctx.beginPath();if(type==='boss'){for(let j=0;j<8;j++){const a=j*Math.PI/4-Math.PI/2,rr=j%2?r*.75:r;ctx.lineTo(Math.cos(a)*rr,Math.sin(a)*rr)}}else if(type==='armor'){ctx.moveTo(-r,-r*.45);ctx.lineTo(0,-r);ctx.lineTo(r,-r*.45);ctx.lineTo(r*.7,r*.7);ctx.lineTo(0,r);ctx.lineTo(-r*.7,r*.7)}else{ctx.moveTo(0,r);ctx.lineTo(-r,-r*.7);ctx.lineTo(0,-r*.2);ctx.lineTo(r,-r*.7)}ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle=color;ctx.fillRect(-2,-3,4,5);if(e.slow>0||e.slowed>0){ctx.beginPath();ctx.arc(0,0,r+4,0,Math.PI*2);ctx.strokeStyle='#8beaf688';ctx.stroke()}if(e.hp<e.maxHp||type==='boss'){ctx.fillStyle='#23313b';ctx.fillRect(-r,-r-8,r*2,3);ctx.fillStyle=color;ctx.fillRect(-r,-r-8,r*2*Math.max(0,e.hp/e.maxHp),3)}ctx.restore()}
for(const b of g.beams||[]){const col=b.color||'#c9ff85';ctx.save();ctx.globalAlpha=Math.min(1,(b.life||.1)*8);if(!reduced){ctx.shadowBlur=14;ctx.shadowColor=col}line(b.x1,b.y1,b.x2,b.y2,col,3);ctx.shadowBlur=0;line(b.x1,b.y1,b.x2,b.y2,'#f4ffe6',1);ctx.fillStyle=col;ctx.beginPath();ctx.arc(b.x2,b.y2,3,0,Math.PI*2);ctx.fill();ctx.restore()}
for(const s of g.shots||[]){ctx.fillStyle='#f799b0';ctx.beginPath();ctx.arc(s.x,s.y,s.radius||3,0,Math.PI*2);ctx.fill()}
for(const fx of g.effects||[]){if(!reduced&&fx.type!=='pulse'){const f=1-fx.life/fx.maxLife;ctx.save();ctx.globalAlpha=1-f;for(let i=0;i<8;i++){const a=i*Math.PI/4+(fx.seed||0);const r=fx.radius+f*26;line(fx.x+Math.cos(a)*r*.65,fx.y+Math.sin(a)*r*.65,fx.x+Math.cos(a)*r,fx.y+Math.sin(a)*r,fx.color,1.5)}ctx.restore()}if(fx.type==='pulse'){ctx.beginPath();ctx.arc(fx.x??240,fx.y??620,fx.radius??(1-(fx.life||0))*300,0,Math.PI*2);ctx.strokeStyle='#b6f59b80';ctx.lineWidth=2;ctx.stroke()}}
if(aim.aimX!=null&&g.state==='running'){ctx.strokeStyle='#d8f6a8';ctx.lineWidth=1;ctx.beginPath();ctx.arc(aim.aimX,aim.aimY,18,0,Math.PI*2);ctx.stroke();for(const d of [-1,1]){line(aim.aimX+d*12,aim.aimY,aim.aimX+d*24,aim.aimY,'#c9f989');line(aim.aimX,aim.aimY+d*12,aim.aimX,aim.aimY+d*24,'#c9f989')}}
ctx.font='8px ui-monospace,monospace';ctx.fillStyle='#779099';ctx.textAlign='center';ctx.fillText('A U R O R A   /   O R B I T A L   S T A T I O N',240,692);
}
function frame(time){const dt=last?Math.min((time-last)/1000,.1):0;last=time;clock+=dt;acc+=dt;if(!paused&&g.state==='running'){while(acc>=1/60){step(g,1/60,aim);acc-=1/60;if(g.state!=='running')break}}else acc=0;if(g.state==='upgrade'&&screen==='running'){sound(750,.18);showUpgrade()}if(['victory','defeat'].includes(g.state)&&screen==='running')end();if(clock>announceUntil)$('announcement').classList.remove('show');draw();sync();requestAnimationFrame(frame)}
title();sync();requestAnimationFrame(frame);
